
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 22 09:57:29 COT 2015
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 15;
  public static final int IGUAL = 16;
  public static final int INT = 8;
  public static final int CHAR = 12;
  public static final int SEMI = 2;
  public static final int CERO = 18;
  public static final int OP_SUMA = 3;
  public static final int STRING = 14;
  public static final int FLOAT = 9;
  public static final int EOF = 0;
  public static final int corchIZQ = 20;
  public static final int INCREMENTO = 17;
  public static final int PARENIZQ = 6;
  public static final int corchDER = 19;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 22;
  public static final int PARENDER = 7;
  public static final int OP_MULT = 5;
  public static final int BOOL = 13;
  public static final int ENTERO = 21;
  public static final int OP_RESTA = 4;
  public static final int FIN = 11;
  public static final int INICIO = 10;
}

